"""
Script that extracts the data obtained from the RYS8833 module log and save it as an excel file.
"""
import os
import re
import logging
import traceback
import datetime
import pandas as pd
import src.log4me
import src.utils

script_name = os.path.basename(__file__).removesuffix(".py")

def open_NMEA_file(file_path: str) -> list:
    """
    Open the log file containing the NMEA sentences and store them as lists inside a single list.

    Args:
        file_path (str): path to the log file containing the NMEA sentences.

    Returns:
        list: list containing lists  with all the NMEA sentences of the log file.
    """
    data = []

    with open(file_path, 'r') as file:
        for line in file:
            data.append(line)

    return data

def NMEA_sentence_filter(NMEA_type: str ,sentences_list: list, filter_list: list) -> list[str]:
    """
    Filters a list containing all NMEA sentences generated by the RYS8833 module.

    Args:
        NMEA_type (str): The type of NMEA sentence to be filtered.

        sentences_list (list): List containing all  NMEA sentences generated by the RYS8833 module.

        filter_list (list): List containing all NMEA sentence filtered by type.

    Returns:
        list[str]: List containing all NMEA sentences  of a specific type generated by the
        RYS8833 module
    """

    for i in range(len(sentences_list)):
        if sentences_list[i][3:6] == NMEA_type:
            filter_list.append(sentences_list[i])

    return filter_list

def get_NMEA_type_attributes(NMEA_type: str) -> list[str]:
    """
    Get the attributes of a specific NMEA sentence type as list to be used as headers for this
    NMEA type dataframe object.

    Args:
        NMEA_type (str): NMEA sentence type whose attributes are gone be fetched.

    Returns:
        list[str]: List containing all attributes of a specific NMEA sentence type.
    """
    NMEA_type_attributes = getattr(src.utils, NMEA_type + "_header")
    return NMEA_type_attributes()

def NMEA_comma_splitter(sentence: str) -> str:
    """
    Split a NMEA sentence string by commas, but ignore exceptions characters listed in
    exceptions_string.

    Args:
        sentence (str): NMEA sentence string to be splited by comma.

    Returns:
        str: NMEA sentence string split by comma with exceptions ignored.
    """
    return re.split(r',(?![KMNT])', sentence)

def manipulate_UTC_of_Position(df_NMEA_type: pd.DataFrame, GMT: int) -> pd.DataFrame:
    """
    Transform the UTC of the position information into the HH:MM:SS format for both UTC
    and local time.

    Args:
        df_NMEA_type (pd.DataFrame): Pandas DataFrame object of a specific NMEA sentence type.

        GMT (int): Greenwich Mean Time (GMT) as an signed integer.

    Returns:
        pd.DataFrame: Pandas DataFrame object of a specific NMEA sentence type.
    """
    if "UTC_of_Position" in df_NMEA_type.columns:
        UTC_of_Position_list = df_NMEA_type["UTC_of_Position"].astype(str).to_list()

        UTC_of_Position_list = \
            [x.split(".")[0] for x in UTC_of_Position_list]
        UTC_of_Position_list = \
            [x[0:2] + ":" + x[2:4] + ":" + x[4:6] for x in UTC_of_Position_list]
        UTC_of_Position_list = \
            [datetime.datetime.strptime(x, "%H:%M:%S").time() for x in UTC_of_Position_list]
        GMT_of_Position_list = \
            [x.replace(hour=x.hour + GMT) for x in UTC_of_Position_list]

        df_NMEA_type["UTC"] = UTC_of_Position_list
        df_NMEA_type["GMT"] = GMT_of_Position_list

        return df_NMEA_type

    else:
        return df_NMEA_type

def NMEA_sentence_to_dataframe(NMEA_type: str,
                               NMEA_type_list: list[str],
                               sheet_name_list: list[str],
                               GMT: int) -> pd.DataFrame:
    """
    Transforms the list of a specified NMEA sentence type into a pandas DataFrame object.

    Args:
        NMEA_type (str): NMEA sentence type whose attributes are gone be fetched.

        NMEA_type_list (list[str]): List of all NMEA sentence types.

        sheet_name_list (list[str]): List of the names of the corresponding excel sheets
        (For each NMEA sentence type the excel sheet should have its name.)

        GMT (int): Greenwich Mean Time (GMT) as an signed integer.

    Returns:
        pd.DataFrame: Pandas DataFrame object of a specific NMEA sentence type.
    """

    # Only generates a dataframe for actual data.
    if len(NMEA_type_list) != 0:
        sheet_name_list.append(NMEA_type)

        # Empty list to store each line of the specific NMEA sentence type as one item
        list_to_frame = []

        # NMEA sentence type attributes to be used as headers for the dataframe of
        # this specific type.
        header_columns = get_NMEA_type_attributes(NMEA_type)

        for i in range(len(NMEA_type_list)):
            item = NMEA_type_list[i]
            list_to_frame.append(NMEA_comma_splitter(item))

        df =  pd.DataFrame(list_to_frame, columns=header_columns)

        df = get_Satellite_System_ID(df)

        manipulate_UTC_of_Position(df, GMT)
        manipulate_measurement_variables(df)

        columns_to_drop = ["Geodial_Separation_[m]",
                            "Age_Of_DGPS_Data",
                            "Checksum",
                            "Course_Over_Ground_Magnetic"]
        for col in columns_to_drop:
            if col in df.columns:
                df.drop(col, axis = 1, inplace = True)
            else:
                continue

        return df

def save_xls(df_list, sheet_list, xls_path) -> None:
    """
    Create an excel file with dataframes specifics to each NMEA sentence type.

    Args:
        df_list (list): The list that has the order each NMEA type was iterated by the
        NMEA_sentence_to_xls() function.

        filename (str): The path and name of the excel file.
    """
    with pd.ExcelWriter(xls_path) as writer:
        for df, sheet in zip(df_list, sheet_list):

            df.to_excel(writer, sheet_name=sheet, startrow=0 , startcol=0)