"""
Script that extracts the data obtained from the RYS8833 module log and save it as an excel file.
"""
import os
import re
import logging
import traceback
import datetime
import pandas as pd
import src.log4me
import src.utils

script_name = os.path.basename(__file__).removesuffix(".py")

def open_NMEA_file(file_path: str) -> list:
    """
    Open the log file containing the NMEA sentences and store them as lists inside a single list.

    Args:
        file_path (str): path to the log file containing the NMEA sentences.

    Returns:
        list: list containing lists  with all the NMEA sentences of the log file.
    """
    data = []

    with open(file_path, 'r') as file:
        for line in file:
            data.append(line)

    return data

def NMEA_sentence_filter(NMEA_type: str ,sentences_list: list, filter_list: list) -> list[str]:
    """
    Filters a list containing all NMEA sentences generated by the RYS8833 module.

    Args:
        NMEA_type (str): The type of NMEA sentence to be filtered.

        sentences_list (list): List containing all  NMEA sentences generated by the RYS8833 module.

        filter_list (list): List containing all NMEA sentence filtered by type.

    Returns:
        list[str]: List containing all NMEA sentences  of a specific type generated by the
        RYS8833 module
    """

    for i in range(len(sentences_list)):
        if sentences_list[i][3:6] == NMEA_type:
            filter_list.append(sentences_list[i])

    return filter_list